server:
  port: 4000


datasource:
  driver-class-name: org.postgresql.Driver #com.mysql.jdbc.Driver
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: toan123
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: clothes

logging:
  level:
    sql: debug

security:
  jwt:
    token:
      secret-key : 9ceb98c291258aef1a13c4b3d54b6a233534bc793dab8427095186898ad13cbf
      token-validity-in-seconds: 3600000