#spring.application.name=api-chatapp
spring:
  application:
    name: api-chatapp
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: ${datasource.driver-class-name}